server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: order
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json

api:
  url:
    pay: http://localhost:8086/payments
