
server:
  port: 8086
  
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: payment
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json


